// Code generated by tygo. DO NOT EDIT.
/**
 * このファイルは `mise run gen-types` が internal/api から生成します。
 * 手で編集しないこと。API の形を変えるときは Go 側の struct を変更してください。
 */

//////////
// source: api.go
/*
Package api defines every type that crosses the HTTP boundary. It is the
single definition of the wire format: the Go handlers use these structs and
the frontend's TypeScript types are generated from this file
(`mise run gen-types`), so the two cannot drift apart.
*/

/**
 * Role decides what an authenticated Discord user may do.
 */
export type Role = string;
/**
 * RoleCreator may submit cards, which opens a pull request for review.
 */
export const RoleCreator: Role = "creator";
/**
 * RoleAdmin may additionally manage the allow list.
 */
export const RoleAdmin: Role = "admin";
/**
 * User is one entry on the allow list. Being logged in with Discord is not
 * enough to submit; a user must also appear here.
 */
export interface User {
  discordId: string;
  displayName: string;
  role: Role;
  addedBy: string;
  createdAt: string;
}
/**
 * SubmissionStatus tracks a pull request through review.
 */
export type SubmissionStatus = string;
export const StatusOpen: SubmissionStatus = "pr_open";
export const StatusMerged: SubmissionStatus = "merged";
export const StatusClosed: SubmissionStatus = "closed";
/**
 * SubmissionCard is one card inside a submitted pull request. A single PR can
 * bundle several cards, possibly across different dataset files.
 */
export interface SubmissionCard {
  kind: string;
  cardId: string;
  cardName: string;
  isEdit: boolean;
}
/**
 * Submission is the audit record of one pull request opened by the CMS.
 */
export interface Submission {
  id: number /* int64 */;
  discordId: string;
  displayName: string;
  branch: string;
  prNumber: number /* int */;
  prUrl: string;
  status: SubmissionStatus;
  cards: SubmissionCard[];
  createdAt: string;
  updatedAt: string;
}
/**
 * Me describes the signed in user to the frontend.
 */
export interface Me {
  discordId: string;
  displayName: string;
  role: Role;
  canSubmit: boolean;
  canManageUsers: boolean;
}
/**
 * Card is one card as the editor sees it. Optional fields are null when the
 * dataset does not carry them.
 */
export interface Card {
  id: string;
  name: string;
  type: string;
  fruit: string;
  description: string;
  /**
   * ImageURL is the site-relative path PPLALE-web stores (e.g.
   * "/images/yojo/x.webp"). It is not directly fetchable by the browser.
   */
  imageUrl: string;
  /**
   * ImageDisplayURL is a full https:// URL the browser can put straight
   * into an <img src>, pointing at the file on PPLALE-web's base branch.
   */
  imageDisplayUrl: string;
  cost: number /* int */;
  hp: number /* int */;
  attack: number /* int */;
  effect?: string;
  role?: string;
  sweetType?: string;
  version?: string;
}
/**
 * CardsResponse is the live content of one dataset file on the base branch.
 */
export interface CardsResponse {
  kind: string;
  nextId: string;
  cards: Card[];
}
/**
 * Dataset describes one card file to the UI.
 */
export interface Dataset {
  kind: string;
  label: string;
  idPrefix: string;
  cardType: string;
  imageDir: string;
}
/**
 * Metadata hands the form its option lists so the UI can never offer a value
 * the backend would reject.
 */
export interface Metadata {
  datasets: Dataset[];
  fruits: string[];
  roles: string[];
  sweetTypes: string[];
  versions: string[];
}
/**
 * SubmitPayload is the JSON part of the multipart submission. The image is
 * sent alongside it as the `image` file field.
 */
export interface SubmitPayload {
  kind: string;
  id: string;
  name: string;
  fruit: string;
  description: string;
  cost: number /* int */;
  hp: number /* int */;
  attack: number /* int */;
  effect?: string;
  role?: string;
  sweetType?: string;
  version?: string;
  imageSlug: string;
}
/**
 * SubmitResult reports the pull request a batch submission opened.
 */
export interface SubmitResult {
  branch: string;
  files: string[];
  prUrl: string;
  prNumber: number /* int */;
  submission?: Submission;
}
/**
 * Draft is one card queued for submission but not yet sent to PPLALE-web. Its
 * image has already been converted to WebP/OGP-PNG so the queue previews
 * exactly what a pull request would contain.
 */
export interface Draft {
  id: number /* int64 */;
  kind: string;
  cardId: string;
  isEdit: boolean;
  name: string;
  fruit: string;
  description: string;
  cost: number /* int */;
  hp: number /* int */;
  attack: number /* int */;
  effect?: string;
  role?: string;
  sweetType?: string;
  version?: string;
  imageSlug: string;
  /**
   * ImageDisplayURL always resolves to something showable: the newly
   * converted draft image when one was uploaded, otherwise the current
   * upstream image for an edit-in-place draft.
   */
  imageDisplayUrl: string;
  hasNewImage: boolean;
  createdAt: string;
}
/**
 * DraftsResponse lists the current user's queued drafts.
 */
export interface DraftsResponse {
  drafts: Draft[];
}
/**
 * SubmitDraftsRequest selects which queued drafts to publish together. An
 * empty/omitted IDs list means "everything currently queued".
 */
export interface SubmitDraftsRequest {
  ids?: number /* int64 */[];
}
/**
 * UsersResponse is the allow list.
 */
export interface UsersResponse {
  users: User[];
}
/**
 * SubmissionsResponse is the audit trail.
 */
export interface SubmissionsResponse {
  submissions: Submission[];
}
/**
 * UpsertUserRequest adds or updates an allow list entry.
 */
export interface UpsertUserRequest {
  displayName: string;
  role: Role;
}
/**
 * StatusResponse is the acknowledgement returned by mutations with no payload.
 */
export interface StatusResponse {
  status: string;
}
/**
 * ErrorResponse is the body of every non 2xx response. Fields carries
 * per-input validation messages so the form can attach them to the right
 * control.
 */
export interface ErrorResponse {
  error: string;
  fields?: { [key: string]: string};
}
